#!/bin/bash -eu

# Build the oldest

git checkout -b devonian $(git rev-list --all | tail -1) # the oldest
echo 'LIBS=-lcrypto -lz' >> Makefile # port to current Ubuntu
make && echo "Success!"
ls
git commit -am"Port first version to $(lsb_release -d | cut -f 2-)" # stash it away

# See where we are

git config --global alias.lo 'log --graph --decorate --oneline'
git lol -5
echo '...'
git lol | tail -5
