#!/bin/bash -eu

git checkout -b devonian $(git rev-list --all | tail -1) # the oldest
echo 'LIBS=-lcrypto -lz' >> Makefile # port to current Ubuntu
make
ls # Eureka!
git commit -am"Port to $(lsb_release -d | cut -f 2-)" # stash it away
git lol # here's our world
