#!/bin/bash -eux

PS4='[\T] '

git clone https://github.com/docker/docker.git
cd docker

git tag -l 'v*.0' | tail -r | while read i; do
  git log -1 --pretty=format:"%D: %x09%ar%n" $i
done | sed 's/tag: //'

